APP_NAME = 'trikonindia'
SECOND_LEVEL_DOMAIN = 'trikonindia'
TOP_LEVEL_DOMAIN = '.com'
URL_PROTOCOL = 'https'
URL_SCHEME = 'https://'
CONTACT_US_EMAIL = 'contact@trikonindia.com'
GOOGLE_SITE_VERIFICATION_CODE = ''
FB_APP_ID = ''
TWITTER_SITE = ''
TWITTER_ID = ''
COUNTRY_CODE = 'IN'
SHARE_THIS_API_URL = 'https://platform-api.sharethis.com/js/sharethis.js#property=5ea53bd759ff750012e54bce&product=sticky-share-buttons'
FULLSTORY_ORG = "VK6V5"
FULLSTORY_NS = "FS"