version : '3'
services:
  vulgar:
    command: ["./devops/staging/run-staging.sh"]
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    env_file: ./devops/staging/.env
    depends_on:
      - db
  db:
    env_file: ./devops/staging/.env
    ports:
      - 5432:5432
    volumes:
      - pg_data_volume:/var/lib/postgresql/data
      - ./db_dumps:/root/db_backup
    restart: always

volumes:
  pg_data_volume: