version : '3'
services:
  vulgar:
    command: ["./devops/staging/run-staging.sh"]
    volumes:
      - .:/usr/src/app
      - static_files:/usr/src/app/static
      - media_files:/usr/src/app/media
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    env_file: ./devops/staging/.env
    depends_on:
      - db
      - nginx
  db:
    env_file: ./devops/staging/.env
    ports:
      - 5432:5432
    volumes:
      - pg_data_volume:/var/lib/postgresql/data
      - ./db_dumps:/root/db_backup
    restart: always
  nginx:
    build:
      context: ./devops/dockerfiles/nginx/.
      dockerfile: Dockerfile_nginx
    volumes:
      - static_files:/static_files
      - media_files:/media_files
    ports:
      - 80:80
    networks:
      - backend
    

volumes:
  pg_data_volume:
  static_files:
  media_files: