# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', 'media_type_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatype',
            name='media_type',
            field=models.CharField(choices=[('document', 'document'), ('image', 'image'), ('video', 'video')], max_length=100),
        ),
    ]
