# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 19:19
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', 'language_display_name_populate'),
    ]

    operations = [
        TrigramExtension()
    ]
