# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0001_auto_20200425_0646'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='media',
        #     name='url',
        #     field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        # ),
    ]
