# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0001_auto_20200616_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglanguage',
            name='title',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
