# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-15 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0002_auto_20200315_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_page_view',
            field=models.BooleanField(default=False),
        ),
    ]
