# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0003_auto_20200621_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglanguage',
            name='breadcrumb_title',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
