# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-15 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0003_category_home_page_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
