# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0004_auto_20200425_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs_hero', to='vulgar.Media'),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs_thumbnail', to='vulgar.Media'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vulgar.Media'),
        ),
    ]
