# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-15 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0004_auto_20200315_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vulgar.Page'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=100),
        ),
    ]
