# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import vulgar.models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0006_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='published_status',
            field=models.CharField(choices=[(vulgar.models.PublishedStatusChoice('Draft'), 'Draft'), (vulgar.models.PublishedStatusChoice('Active'), 'Active'), (vulgar.models.PublishedStatusChoice('Inactive'), 'Inactive')], default='Active', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='published_status',
            field=models.CharField(choices=[(vulgar.models.PublishedStatusChoice('Draft'), 'Draft'), (vulgar.models.PublishedStatusChoice('Active'), 'Active'), (vulgar.models.PublishedStatusChoice('Inactive'), 'Inactive')], default='Active', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_status',
            field=models.CharField(choices=[(vulgar.models.PublishedStatusChoice('Draft'), 'Draft'), (vulgar.models.PublishedStatusChoice('Active'), 'Active'), (vulgar.models.PublishedStatusChoice('Inactive'), 'Inactive')], default='Active', max_length=100),
        ),
    ]
