# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-30 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0007_auto_20200425_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='display_name',
            field=models.CharField(db_index=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='social_media_image',
            field=models.ForeignKey(blank=True, help_text='Minimum dimension - 1200×630 pixels, aspect ratio - 1.91:1, Size < 1MB', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blogs_social_media', to='vulgar.Media'),
        ),
        migrations.AlterField(
            model_name='category',
            name='social_media_image',
            field=models.ForeignKey(blank=True, help_text='Minimum dimension - 1200×630 pixels, aspect ratio - 1.91:1, Size < 1MB', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories_social_media', to='vulgar.Media'),
        ),
    ]
