# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-20 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0008_auto_20200320_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
