# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-25 17:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0015_auto_20200321_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None), blank=True, null=True, size=None),
        ),
    ]
