# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0019_category_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
