# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0021_auto_20200326_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta_keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
    ]
