# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0023_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
    ]
