# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('vulgar', '0024_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country',
            field=models.ManyToManyField(to='cities_light.Country'),
        ),
    ]
