# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-26 19:11
from __future__ import unicode_literals

from django.db import migrations

def generate_language(apps, schema_editor):
    Language = apps.get_model('vulgar', 'Language')
    Country = apps.get_model('cities_light', 'Country')
    IndiaCountry = Country.objects.filter(slug='india').last()
    language_list = [
        {
            'name': 'English',
            'code': 'EN',
            'slug': 'en'
        },
        {
            'name': 'Hindi',
            'code': 'HI',
            'slug': 'hi'
        },
        {
            'name': 'Bengali',
            'code': 'BN',
            'slug': 'bn'
        },
        {
            'name': 'Assamese',
            'code': 'AS',
            'slug': 'as'
        },
        {
            'name': 'Gujarati',
            'code': 'GU',
            'slug': 'gu'
        },
        {
            'name': 'Kannada',
            'code': 'KN',
            'slug': 'kn'
        },
        {
            'name': 'Malayalam',
            'code': 'ML',
            'slug': 'ml'
        },
        {
            'name': 'Marathi',
            'code': 'MR',
            'slug': 'mr'
        },
        {
            'name': 'Nepali',
            'code': 'NE',
            'slug': 'ne'
        },
        {
            'name': 'Oriya',
            'code': 'OR',
            'slug': 'or'
        },
        {
            'name': 'Punjabi',
            'code': 'PA',
            'slug': 'pa'
        },
        {
            'name': 'Sindhi',
            'code': 'SD',
            'slug': 'sd'
        },
        {
            'name': 'Tamil',
            'code': 'TA',
            'slug': 'ta'
        },
        {
            'name': 'Telugu',
            'code': 'TE',
            'slug': 'te'
        },
        {
            'name': 'Urdu',
            'code': 'UR',
            'slug': 'ur'
        },
        {
            'name': 'Bihari',
            'code': 'BH',
            'slug': 'bh'
        }
    ]

    for language in language_list:
        l = Language(name = language['name'], code = language['code'], slug=language['slug'])
        l.save()
        l.country.add(IndiaCountry)


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0025_language_country'),
    ]

    operations = [
        migrations.RunPython(generate_language),
    ]
