# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0026_languate_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=1000)),
                ('breadcrumb_title', models.CharField(default='', max_length=20)),
                ('meta_keywords', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('meta_description', models.CharField(default='', max_length=1000)),
                ('description', models.CharField(default='', max_length=1000)),
                ('content', models.CharField(max_length=100000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('meta_keywords', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('meta_description', models.CharField(default='', max_length=1000)),
                ('category_description', models.CharField(default='', max_length=1000)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vulgar.Category')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vulgar.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vulgar.Language'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='blogss', to='vulgar.Tag'),
        ),
        migrations.AddField(
            model_name='bloglanguage',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vulgar.Blog'),
        ),
        migrations.AddField(
            model_name='bloglanguage',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vulgar.User'),
        ),
        migrations.AddField(
            model_name='bloglanguage',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vulgar.Language'),
        ),
        migrations.AddField(
            model_name='bloglanguage',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='vulgar.Tag'),
        ),
    ]
