# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0029_auto_20200330_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
