# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-30 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0032_auto_20200330_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taglanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.DeleteModel(
            name='TagLanguage',
        ),
    ]
