# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0033_auto_20200330_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('alt_tag', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
