# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0035_auto_20200425_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('alt_tag', models.CharField(max_length=100)),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vulgar.MediaType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
