# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 06:29
from __future__ import unicode_literals

from django.db import migrations

def populate_media_type(apps, schema_editor):
    MediaType = apps.get_model('vulgar', 'MediaType')
    media_type_list = ['document', 'image', 'video']

    for media_type in media_type_list:
        mt = MediaType(media_type = media_type)
        mt.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vulgar', '0036_media'),
    ]

    operations = [
        migrations.RunPython(populate_media_type),
    ]
